name: Analyze, Build and Deploy

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  sonar:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Récupération du code source
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Étape 2 : Configuration de Java
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin

      # Étape 3 : Analyse SonarCloud
      - name: Run SonarCloud Analysis
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=AhmedJallali_calc-CI-CD
            -Dsonar.organization=ahmedjallali
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.sources=.
            -Dsonar.exclusions=**/node_modules/**,**/dist/**

  docker:
    name: Build and Push Docker Image
    needs: sonar
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Configuration de Docker
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Étape 2 : Récupération du code source
      - name: Checkout code
        uses: actions/checkout@v2

      # Étape 3 : Build et Push de l'image Docker
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: ./sources
          file: ./sources/Dockerfile
          push: true
          tags: ahmedjallali/devopsproject:1.0.${{ github.run_number }}

  build-and-deploy-2:
    name: Build and Deploy to Azure App Service
    needs: docker
    runs-on: ubuntu-latest
    if: success()

    steps:
      # Étape 1 : Récupération du code source
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Connexion à Azure
      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: mp2lacr.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # Étape 3 : Transférer l'image Docker à Azure Container Registry
      - name: Pull Docker Image from DockerHub and Push to ACR
        run: |
          docker pull ahmedjallali/devopsproject:1.0.${{ github.run_number }}
          docker tag ahmedjallali/devopsproject:1.0.${{ github.run_number }} mp2lacr.azurecr.io/mp2l:${{ github.sha }}
          docker push mp2lacr.azurecr.io/mp2l:${{ github.sha }}

      # Étape 4 : Déploiement dans Azure App Service
      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: mp2lwebapp2
          images: mp2lacr.azurecr.io/mp2l:${{ github.sha }}

      # Étape 5 : Déconnexion d'Azure
      - name: Azure Logout
        run: |
          az logout
